window.APP_JUNKY_PROJECTS = [
  {
    title: "Focus Forge",
    date: "2026-06-04",
    type: "tool",
    status: "Prototype",
    summary: "A focused work-session tool with a timer, task list, and simple session score.",
    tags: ["productivity", "timer", "daily tool"],
    localPath: "../projects/2026-06-04-focus-forge/index.html",
    repoUrl: "https://github.com/Nubles/app-junky-focus-forge",
    liveUrl: "https://nubles.github.io/app-junky-focus-forge/",
    accent: "#0f766e"
  },
  {
    title: "Signal Garden",
    date: "2026-06-05",
    type: "game",
    status: "Prototype",
    summary: "A compact arcade game about delivering colored signal seeds to matching beacons before charge runs out.",
    tags: ["arcade", "canvas", "daily game"],
    localPath: "../projects/2026-06-05-signal-garden/index.html",
    repoUrl: "https://github.com/Nubles/app-junky-signal-garden",
    liveUrl: "https://nubles.github.io/app-junky-signal-garden/",
    accent: "#fbbf24"
  },
  {
    title: "Decision Loom",
    date: "2026-06-05",
    type: "tool",
    status: "Prototype",
    summary: "A weighted decision matrix for ranking options by criteria, scores, and a copyable summary.",
    tags: ["decision", "planning", "daily tool"],
    localPath: "../projects/2026-06-05-decision-loom/index.html",
    repoUrl: "https://github.com/Nubles/app-junky-decision-loom",
    liveUrl: "https://nubles.github.io/app-junky-decision-loom/",
    accent: "#115e59"
  },
  {
    title: "Prism Relay",
    date: "2026-06-05",
    type: "game",
    status: "Prototype",
    summary: "A compact mirror-rotation puzzle about routing a beam from emitter to receiver.",
    tags: ["puzzle", "logic", "daily game"],
    localPath: "../projects/2026-06-05-prism-relay/index.html",
    repoUrl: "https://github.com/Nubles/app-junky-prism-relay",
    liveUrl: "https://nubles.github.io/app-junky-prism-relay/",
    accent: "#2563eb"
  },
  {
    title: "Launch Lantern",
    date: "2026-06-05",
    type: "tool",
    status: "Prototype",
    summary: "A release-readiness checklist that turns App Junky prototypes into GitHub Pages launches.",
    tags: ["release", "checklist", "daily tool"],
    localPath: "../projects/2026-06-05-launch-lantern/index.html",
    repoUrl: "https://github.com/Nubles/app-junky-launch-lantern",
    liveUrl: "https://nubles.github.io/app-junky-launch-lantern/",
    accent: "#0f766e"
  },
  {
    title: "Orbit Orchard",
    date: "2026-06-06",
    type: "game",
    status: "Prototype",
    summary: "A compact timing game about catching fruit as it drifts through orbital lanes.",
    tags: ["arcade", "timing", "daily game"],
    localPath: "../projects/2026-06-06-orbit-orchard/index.html",
    repoUrl: "https://github.com/Nubles/app-junky-orbit-orchard",
    liveUrl: "https://nubles.github.io/app-junky-orbit-orchard/",
    accent: "#34d399"
  },
  {
    title: "Favorbound Companion",
    date: "2026-06-06",
    type: "tool",
    status: "Prototype",
    summary: "An OSRS restrictive-playthrough companion for faction-bound rules, Favor tracking, duties, and alliance unlocks.",
    tags: ["osrs", "favorbound", "companion"],
    repoUrl: "https://github.com/Nubles/OSRS-Favorbound-Companion",
    liveUrl: "https://nubles.github.io/OSRS-Favorbound-Companion/",
    accent: "#d59b45"
  },
  {
    title: "Rail Warden",
    date: "2026-06-06",
    type: "game",
    status: "Prototype",
    summary: "A compact switch-routing puzzle about guiding colored carts into matching depots.",
    tags: ["puzzle", "routing", "daily game"],
    localPath: "../projects/2026-06-06-rail-warden/index.html",
    repoUrl: "https://github.com/Nubles/app-junky-rail-warden",
    liveUrl: "https://nubles.github.io/app-junky-rail-warden/",
    accent: "#38bdf8"
  },
  {
    title: "Idea Kiln",
    date: "2026-06-07",
    type: "tool",
    status: "Prototype",
    summary: "A small idea-shaping workspace that scores rough sparks and creates copyable prototype briefs.",
    tags: ["planning", "ideas", "daily tool"],
    localPath: "../projects/2026-06-07-idea-kiln/index.html",
    repoUrl: "https://github.com/Nubles/app-junky-idea-kiln",
    liveUrl: "https://nubles.github.io/app-junky-idea-kiln/",
    accent: "#2563eb"
  },
  {
    title: "Routebound Companion",
    date: "2026-06-07",
    type: "tool",
    status: "Prototype",
    summary: "An OSRS restrictive-playthrough companion for route-locked travel, checkpoints, permits, and breach notes.",
    tags: ["osrs", "routebound", "companion"],
    repoUrl: "https://github.com/Nubles/OSRS-Routebound",
    liveUrl: "https://nubles.github.io/OSRS-Routebound/",
    accent: "#55afba"
  },
  {
    title: "Tide Courier",
    date: "2026-06-07",
    type: "game",
    status: "Prototype",
    summary: "A compact lane-and-timing game about ferrying parcels through shifting tide currents.",
    tags: ["arcade", "timing", "daily game"],
    localPath: "../projects/2026-06-07-tide-courier/index.html",
    repoUrl: "https://github.com/Nubles/app-junky-tide-courier",
    liveUrl: "https://nubles.github.io/app-junky-tide-courier/",
    accent: "#0891b2"
  }
];
